spring.application.name=fnn
spring.datasource.url=jdbc:h2:file:./data/models
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true